[project]
name = "sae-3d-gallery-search"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "chromadb",
    "fastapi>=0.141.1",
    "httpx",
    "python-multipart",
    "uvicorn"
]

[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"
]

[tool.pytest.ini_options]
pythonpath = ["src"]